@startuml Learninghouse Model
class Connector {
    uuid: str
    name: str
}

interface Resource {
    uuid: str
    connector: Connector
    capabilities: List[Capability]
}

Connector <--* "1" Resource

abstract class Capability{
    name: str
    value: CapabilityValue
}

Resource "0..*" *--> Capability

class SensorCapability {
    use_as_training_data: bool
}

SensorCapability --|> Capability

class ActuatorCapability {
    brain: Brain | None
}

ActuatorCapability --|> Capability

interface CapabilityValue {
    raw: Any
    typed: CapabilityType
}

Capability "1" *--> CapabilityValue

enum CapabilityValueType {
    NUMERICAL
    CATEGORICAL
}

CapabilityValue "1" *--> CapabilityValueType

class GenericStringValue {
    raw: str | None
    typed: CapabilityValueType.CATEGORICAL
}

GenericStringValue ..|> CapabilityValue : implements

class GenericNumberValue {
    raw: float | None
    unit_of_measurement: Unit
    typed: 
}

enum Unit {
    AMPERE
    CANDELA
    CELSIUS
    COULOMB
    FARAD
    GRAM
    HERTZ
    JOULE
    KELVIN
    LUMEN
    LUX
    METER
    MOLE
    NEWTON
    OHM
    PASCAL
    RADIAN
    SECOND
    SIEMENS
    STERADIAN
    TESLA
    VOLT
    WATT
    WEBER
}

GenericNumberValue "1" *--> Unit

GenericNumberValue ..|> CapabilityValue : implements

class TemperatureValue {
    typed: CapabilityValueType.NUMERICAL
    unit_of_measurement: Unit.CELSIUS | Unit.KELVIN
}

TemperatureValue --|> GenericNumberValue

class PressureValue {
    typed: CapabilityValueType.NUMERICAL
    unit_of_measurement: Unit.PASCAL
}

PressureValue --|> GenericNumberValue

class GenericBooleanValue {
    raw: bool | None
    typed: CapabilityValueType.CATEGORICAL
}

GenericBooleanValue ..|> CapabilityValue : implements

class SwitchValue {
}

SwitchValue --|> GenericBooleanValue

class ResourceGrouping {
    name: str
}

ResourceGrouping <--* "1" Resource
Location --|> ResourceGrouping
Weatherstation --|> ResourceGrouping
Person --|> ResourceGrouping

@enduml