os: linux
dist: focal
language: shell
branches:
  only:
    - master
before_install:
  - set -e
  # Configure environment so changes are picked up when the Docker daemon is restarted after upgrading
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  # Upgrade to Docker CE 19.03 for BuildKit support
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce=5:19.03.12~3-0~ubuntu-focal # pin version for reproducibility
  - docker info
  - docker buildx create --name builder --use
  - docker buildx ls
install:
  - echo "-------- Dockerfile $VERSION --------";
  - cat Dockerfile;
  - build_arg_options="--build-arg BUILD_DATE=$(date +"%Y-%m-%dT%H:%M:%SZ") --build-arg VCS_REF=$TRAVIS_COMMIT --build-arg VERSION=$VERSION"
  - tag_options="--tag learninghouseservice/learninghouse:latest --tag learninghouseservice/learninghouse:$VERSION"
  - build_options="$build_arg_options --platform "linux/amd64" $tag_options --progress plain"
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
        docker buildx build $build_options --push .;
    else
        docker buildx build $build_options .;
    fi
matrix:
  fast_finish: true
env:
  matrix:
    - VERSION=0.9.2
