name: build-project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.7'
          - '3.9'
          - '3.10'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install build package
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
      working-directory: core