name: build-project

on: [push, pull_request]

jobs:
  build-ui: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: ui

    - name: Write version to file
      run: node git-version.js
      working-directory: ui

    - name: Build
      run: npm run build:core
      working-directory: ui

    - name: Save angular artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ui-artifacts
        path: |
          ui/dist/learninghouse
    
  build-core:
    runs-on: ubuntu-latest
    needs: build-ui
    strategy:
      matrix:
        python-version:
          - '3.7'
          - '3.9'
          - '3.10'
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Integrate UI
      uses: actions/download-artifact@v3
      with:
        name: ui-artifacts
        path: core/learninghouse/ui

    - name: Install build package
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build
      working-directory: core

    - name: Save python artifacts
      uses: actions/upload-artifact@v3
      with:
        name: python-artifacts-${{ matrix.python-version }}
        path: |
          core/dist